---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingressdev
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: dev.devopstack.biz
    http:
      paths:
        - path: /
          backend:
            serviceName: devservice
            servicePort: 5000
