---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingressprod
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: prod.devopstack.biz
    http:
      paths:
        - path: /
          backend:
            serviceName: prodservice
            servicePort: 9000